import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/billpay.htm');
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('john');
  await page.locator('input[name="password"]').click();
  await page.pause();
  await page.locator('input[name="password"]').fill('demo');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Bill Pay' }).click();
  await page.locator('input[name="payee.name"]').click();
  await page.locator('input[name="payee.name"]').fill('user01');
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').fill('User02');
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('USer03');
  await page.locator('input[name="payee.address.state"]').click();
  await page.locator('input[name="payee.address.state"]').fill('USer04');
  await page.locator('input[name="payee.address.zipCode"]').click();
  await page.locator('input[name="payee.address.zipCode"]').fill('46546');
  await page.locator('input[name="payee.phoneNumber"]').click();
  await page.locator('input[name="payee.phoneNumber"]').fill('456464');
  await page.locator('input[name="payee.accountNumber"]').click();
  await page.locator('input[name="payee.accountNumber"]').fill('123');
  await page.locator('input[name="verifyAccount"]').click();
  await page.locator('input[name="verifyAccount"]').fill('1234');
  await page.getByRole('row', { name: 'Amount: $' }).getByRole('cell').nth(1).click();
  await page.locator('input[name="amount"]').fill('5000');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('The account numbers do not')).toBeVisible();
  await page.locator('input[name="payee.accountNumber"]').click();
  await page.locator('input[name="payee.accountNumber"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.locator('input[name="payee.accountNumber"]')).toBeVisible();
  await page.locator('input[name="payee.accountNumber"]').click();
  await page.locator('input[name="payee.accountNumber"]').fill('1234');
  await page.locator('input[name="verifyAccount"]').click();
  await page.locator('input[name="verifyAccount"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.locator('#validationModel-verifyAccount-empty')).toBeVisible();
});