import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://parabank.parasoft.com/parabank/index.htm?ConnType=JDBC');
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('john');
  await page.locator('input[name="password"]').click();
  await page.locator('input[name="password"]').fill('demo');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('link', { name: 'Bill Pay' }).click();
  await expect(page.getByRole('heading', { name: 'Bill Payment Service' })).toBeVisible();
  await page.getByText('Enter payee information').click();
  await expect(page.getByText('Enter payee information')).toBeVisible();
  await page.locator('input[name="payee.name"]').click();
  await page.locator('input[name="payee.name"]').fill('S');
  await page.getByRole('row', { name: 'Address:' }).getByRole('cell').nth(1).click();
  await page.locator('input[name="payee.address.street"]').fill('S');
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('S');
  await page.locator('input[name="payee.address.state"]').click();
  await page.locator('input[name="payee.address.state"]').fill('S');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('Zip Code is required.')).toBeVisible();
  await expect(page.getByText('Phone number is required.')).toBeVisible();
  await expect(page.locator('#validationModel-account-empty')).toBeVisible();
  await expect(page.locator('#validationModel-verifyAccount-empty')).toBeVisible();
  await expect(page.getByText('The amount cannot be empty.')).toBeVisible();
  await page.locator('input[name="payee.address.state"]').click();
  await page.locator('input[name="payee.address.state"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('State is required.')).toBeVisible();
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('City is required.')).toBeVisible();
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('Address is required.')).toBeVisible();
  await page.getByRole('table').click();
  await page.locator('input[name="payee.name"]').click();
  await page.locator('input[name="payee.name"]').fill('');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('Payee name is required.')).toBeVisible();
  await page.locator('input[name="payee.name"]').click();
  await page.locator('input[name="payee.name"]').fill('Adam');
  await page.locator('input[name="payee.address.street"]').click();
  await page.locator('input[name="payee.address.street"]').fill('AA');
  await page.locator('input[name="payee.address.city"]').click();
  await page.locator('input[name="payee.address.city"]').fill('AA');
  await page.locator('input[name="payee.address.state"]').click();
  await page.locator('input[name="payee.address.state"]').fill('AA');
  await page.locator('input[name="payee.address.zipCode"]').click();
  await page.locator('input[name="payee.address.zipCode"]').fill('4222');
  await page.locator('input[name="payee.phoneNumber"]').click();
  await page.locator('input[name="payee.phoneNumber"]').fill('2222');
  await page.locator('input[name="payee.accountNumber"]').click();
  await page.locator('input[name="payee.accountNumber"]').fill('1111');
  await page.locator('input[name="verifyAccount"]').click();
  await page.locator('input[name="verifyAccount"]').fill('2222');
  await page.getByRole('table').click();
  await page.locator('input[name="amount"]').click();
  await page.locator('input[name="amount"]').fill('5000');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByText('The account numbers do not')).toBeVisible();
  await page.locator('input[name="verifyAccount"]').click();
  await page.locator('input[name="verifyAccount"]').fill('1111');
  await page.getByRole('button', { name: 'Send Payment' }).click();
  await expect(page.getByRole('heading', { name: 'Bill Payment Complete' })).toBeVisible();
  await expect(page.getByText('Bill Payment to Adam in the')).toBeVisible();
});